export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_SEARCHED_BOOKS = 'UPDATE_SEARCHED_BOOKS';
export const UPDATE_SAVED_BOOKS = 'UPDATE_SAVED_BOOKS';
export const UPDATE_READ = 'UPDATE_READ';
export const UPDATE_FAVOURITE = 'UPDATE_FAVOURITE';
export const REMOVE_BOOK_FROM_SAVED = 'REMOVE_BOOK_FROM_SAVED';